wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1749622380
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      - 24
      - 37
      4: 3.12.0
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 22
learning_rate:
  desc: null
  value: 0.001
type:
  desc: null
  value: attention
